### ISSUE TITLE
Add proper API for enabling FIFO stream

### ISSUE THREAD

**Issue by tannewt** [adafruit/Adafruit_CircuitPython_LIS3DH#14]
The CircuitPlayground driver uses direct write to the device with `_write_register_byte` which should be replaced by a self-documenting method call.

From the CircuitPlayground driver:
```python
self._lis3dh._write_register_byte(adafruit_lis3dh.REG_CTRL5, 0b01001000)
self._lis3dh._write_register_byte(0x2E, 0b10000000)
```

**Comment by tdicola** [comment]
Closing because this isn't necessary with the latest circuit playground library code anymore.  Originally the circuit playground code made these FIFO mode changes because it was based on fidget spinner example code.  However the circuit playground library never needed to use the FIFO mode and later updates to it removed the calls and interact with the LIS3DH only using its current public interface.  Closing as it's not a priority to support complex FIFO stream mode outside one-off examples.
